# Generated by Django 5.2.7 on 2025-11-02 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('estimation', models.PositiveSmallIntegerField(default=5, error_messages={'max_value': 'Значение больше 5.', 'min_value': 'Значение меньше 1.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
