# Generated by Django 5.2.7 on 2025-11-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
